import { FormEvent, useMemo, useRef, useState } from 'react';
import { clearConnection, loadConnection, saveConnection } from '../hermes/auth';
import { HermesClient } from '../hermes/client';
import { supportsResponses } from '../hermes/capabilities';
import { streamResponse } from '../hermes/responses';
import type { HermesCapabilities, HermesConnectionProfile } from '../hermes/types';

type Message = { role: 'user' | 'assistant'; text: string };
export function HermesChatPage() {
  const initial = loadConnection(); const [profile, setProfile] = useState<HermesConnectionProfile | null>(initial); const [url, setUrl] = useState(initial?.baseUrl ?? 'https://'); const [key, setKey] = useState(initial?.apiKey ?? ''); const [allowInsecure, setAllowInsecure] = useState(initial?.allowInsecure ?? false); const [capabilities, setCapabilities] = useState<HermesCapabilities | null>(null); const [error, setError] = useState(''); const [connecting, setConnecting] = useState(false); const [input, setInput] = useState(''); const [messages, setMessages] = useState<Message[]>([]); const [streaming, setStreaming] = useState(false); const previousId = useRef<string | undefined>(undefined); const abort = useRef<AbortController | undefined>(undefined);
  const client = useMemo(() => profile ? new HermesClient(profile) : null, [profile]);
  async function connect(e: FormEvent) { e.preventDefault(); setConnecting(true); setError(''); try { const next = { baseUrl: url, apiKey: key, allowInsecure }; const candidate = new HermesClient(next); await candidate.health(); const caps = await candidate.fetchCapabilities(); if (!supportsResponses(caps)) throw new Error('This Hermes server does not advertise the Responses API required by this client'); saveConnection(next); setProfile(next); setCapabilities(caps); } catch (err) { setError(err instanceof Error ? err.message : String(err)); } finally { setConnecting(false); } }
  async function send(e: FormEvent) { e.preventDefault(); const text = input.trim(); if (!client || !text || streaming) return; setInput(''); setMessages((m) => [...m, { role: 'user', text }, { role: 'assistant', text: '' }]); setStreaming(true); setError(''); const controller = new AbortController(); abort.current = controller; try { for await (const event of streamResponse(client, text, { previousResponseId: previousId.current, signal: controller.signal })) { if (event.delta) setMessages((m) => m.map((x, i) => i === m.length - 1 ? { ...x, text: x.text + event.delta } : x)); if (event.response?.id) previousId.current = event.response.id; if (event.type === 'error') throw new Error(typeof event.error === 'string' ? event.error : 'Hermes response failed'); } } catch (err) { if (!(err instanceof DOMException && err.name === 'AbortError')) setError(err instanceof Error ? err.message : String(err)); } finally { setStreaming(false); abort.current = undefined; } }
  if (!profile) return <main className="h-full overflow-auto p-8"><div className="max-w-xl mx-auto"><h1 className="text-2xl font-semibold mb-2">Hermes Desktop</h1><p className="mb-6" style={{ color: 'var(--color-text-secondary)' }}>Connect to your existing Hermes API. The key is kept only in memory/sessionStorage in Phase A; Windows Credential Manager is Phase B.</p><form onSubmit={connect} className="space-y-4"><label className="block">API base URL<input className="block w-full mt-1 p-3 rounded border bg-transparent" value={url} onChange={e => setUrl(e.target.value)} /></label><label className="block">API key<input type="password" className="block w-full mt-1 p-3 rounded border bg-transparent" value={key} onChange={e => setKey(e.target.value)} /></label><label className="flex gap-2"><input type="checkbox" checked={allowInsecure} onChange={e => setAllowInsecure(e.target.checked)} />Explicitly allow insecure HTTP for a remote host</label>{error && <p role="alert" className="text-red-500">{error}</p>}<button disabled={connecting} className="px-4 py-2 rounded bg-blue-600 text-white">{connecting ? 'Connecting…' : 'Connect'}</button></form></div></main>;
  return <main className="flex flex-col h-full"><header className="p-3 border-b flex justify-between"><span>Hermes {capabilities?.profile ? `· ${capabilities.profile}` : ''}</span><button onClick={() => { clearConnection(); setProfile(null); setCapabilities(null); }}>Disconnect</button></header><section className="flex-1 overflow-auto max-w-3xl w-full mx-auto p-5 space-y-4">{messages.length === 0 && <p style={{ color: 'var(--color-text-secondary)' }}>Connected. Send a message to Hermes.</p>}{messages.map((m, i) => <div key={i} className={`p-3 rounded ${m.role === 'user' ? 'ml-16 bg-blue-600 text-white' : 'mr-16'}`} style={m.role === 'assistant' ? { background: 'var(--color-bg-secondary)' } : undefined}><strong>{m.role === 'user' ? 'You' : 'Hermes'}</strong><div className="whitespace-pre-wrap">{m.text || (streaming && i === messages.length - 1 ? '…' : '')}</div></div>)}</section>{error && <p role="alert" className="text-red-500 max-w-3xl w-full mx-auto px-5">{error}</p>}<form onSubmit={send} className="max-w-3xl w-full mx-auto p-4 flex gap-2"><textarea aria-label="Message Hermes" className="flex-1 p-3 rounded border bg-transparent" value={input} onChange={e => setInput(e.target.value)} /><button type={streaming ? 'button' : 'submit'} onClick={streaming ? () => abort.current?.abort() : undefined} className="px-4 rounded bg-blue-600 text-white">{streaming ? 'Stop' : 'Send'}</button></form></main>;
}
